### PR TITLE
Demo1 Pull Request

### PR DESCRIPTION
**Pull request by ghinwabadawi1**

### CODE REVIEW

**Comment by scoheb** [comment]
some notes:
- items such as .idea, /bin should not be committed.
- consider use a .gitignore next time.

**Comment by ghinwabadawi1** [comment]
@scoheb ok thanks for the tip

**Comment by danielyinanc** [comment]
I concur .idea /bin /target can be excluded.

git rm -rf .idea is the way to remove them from git and committing the final outcome.. consider experimenting with it.

**Comment by ghinwabadawi1** [comment]
@danielyinanc  yea sure, thanks for the feedback

**Comment by danielyinanc** [comment]
Another important point is to put a README describing 
Day 1 
HelloWorld -- file1, file2
WorkQueues -- file3, file4

It will make easier to read... especially since you are planning to use one project for the entire week.

**Pull request closed without merging**
